name:                haskell-exercises-shmup
version:             0.1.0.0
github:              "githubuser/haskell-exercises-shmup"
license:             GPL-3
author:              "Farhad Mehta"
maintainer:          "farhad.mehta@ost.ch"
copyright:           "2023 Farhad Mehta"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README at <https://github.com/githubuser/haskell-exercises-shmup#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - QuickCheck
    - hspec
    - prettyprinter
    # - quickspec

executables:
  haskell-exercises-shmup-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-exercises-shmup

tests:
  haskell-exercises-shmup-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-exercises-shmup
    - hspec
    - QuickCheck
    - genvalidity-hspec
    - prettyprinter
    # - quickspec